// Configuration for Control Panel
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 25004,
    channelName : "russaklive",
    auth        : "JF0kZ0e1wOd15szGTZhA2ukC0hEq9X",
    http        : "https://"
};

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
